services:
  # Backend API Service
  - type: web
    name: sassou-ecommerce-api
    runtime: node
    plan: starter
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: REDIS_URL
        fromService:
          name: sassou-ecommerce-redis
          type: keyvalue
          property: connectionString

  # Redis Cache Service
  - type: keyvalue
    name: sassou-ecommerce-redis
    plan: starter
    region: oregon
    ipAllowList: []

  # Frontend Static Site
  - type: web
    name: sassou-ecommerce-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist